name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  pytest:
    name: Pytest
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      - name: Run pytest
        run: pixi run test-coverage --color=yes

  check-schema-changes:
    name: Check for Schema Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      - name: Regenerate the schema
        run: pixi run schema
      - name: Check for schema changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]
          then
            echo "::error::The schema is out of date. Please run 'pixi run schema' and commit the changes."
            exit 1
          fi

  check-requirements-txt:
    name: Check requirements.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          run-install: false
      - name: Sync to requirements.txt
        run: ./.github/scripts/sync-deps.sh
      - name: Check for changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]
          then
            echo "::error::The requirements.txt is out of date. Please run './.github/scripts/sync-deps.sh' and commit the changes."
            exit 1
          fi

  check-deps:
    name: Check pixi.toml in sync with pyproject.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          run-install: false
      - name: Check Dependencies
        run: ./.github/scripts/check-deps.sh
