name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-schema-changes:
    name: Check for Schema Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      - name: Regenerate the schema
        run: pixi run schema
      - name: Check for schema changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]
          then
            echo "::error::The schema is out of date. Please run 'pixi run schema' and commit the changes."
            exit 1
          fi

  check-requirements-txt:
    name: Check requirements.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          run-install: false
      - name: Sync to requirements.txt
        run: ./.github/scripts/sync-deps.sh
      - name: Check for changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]
          then
            echo "::error::The requirements.txt is out of date. Please run './.github/scripts/sync-deps.sh' and commit the changes."
            exit 1
          fi

  check-deps:
    name: Check pixi.toml in sync with pyproject.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          run-install: false
      - name: Check Dependencies
        run: ./.github/scripts/check-deps.sh
